demo/f1/f1Server/config/routes.rb
F1Server::Application.routes.draw do
  resources :scannings

  root :to => 'scannings#index'
  
  match 'api/api_scan' => 'scannings#index1'
  
  

end

demo/f1/f1Server/app/models/scanning.rb
class Scanning < ActiveRecord::Base
  attr_accessible :scanDate, :scanTitle, :scanUrl
end

demo/f1/f1Server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo/f1/f1Server/app/controllers/scannings_controller.rb
class ScanningsController < ApplicationController
  # GET /scannings
  # GET /scannings.json
  def index
    @scannings = Scanning.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scannings }
    end
  end


  def index1
    
    @scannings = Scanning.find_by_sql("select scanUrl,scanDate ,scanTitle from scannings")  

    @j = { :a =>'succss',  :b =>  @scannings}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @j }
    end
  end
  # GET /scannings/1
  # GET /scannings/1.json
  def show
    @scanning = Scanning.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scanning }
    end
  end

  # GET /scannings/new
  # GET /scannings/new.json
  def new
    @scanning = Scanning.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scanning }
    end
  end

  # GET /scannings/1/edit
  def edit
    @scanning = Scanning.find(params[:id])
  end

  # POST /scannings
  # POST /scannings.json
  def create
    @scanning = Scanning.new(params[:scanning])

    respond_to do |format|
      if @scanning.save
        format.html { redirect_to @scanning, notice: 'Scanning was successfully created.' }
        format.json { render json: @scanning, status: :created, location: @scanning }
      else
        format.html { render action: "new" }
        format.json { render json: @scanning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scannings/1
  # PUT /scannings/1.json
  def update
    @scanning = Scanning.find(params[:id])

    respond_to do |format|
      if @scanning.update_attributes(params[:scanning])
        format.html { redirect_to @scanning, notice: 'Scanning was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scanning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scannings/1
  # DELETE /scannings/1.json
  def destroy
    @scanning = Scanning.find(params[:id])
    @scanning.destroy

    respond_to do |format|
      format.html { redirect_to scannings_url }
      format.json { head :no_content }
    end
  end
end

demo/f1/f1Server/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/f1/f1Server/app/helpers/scannings_helper.rb
module ScanningsHelper
end

demo/f1/f1Server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>F1Server</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/f1/f1Server/app/views/scannings/_form.html.erb
<%= form_for(@scanning) do |f| %>
  <% if @scanning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scanning.errors.count, "error") %> prohibited this scanning from being saved:</h2>

      <ul>
      <% @scanning.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scanUrl %><br />
    <%= f.text_field :scanUrl %>
  </div>
  <div class="field">
    <%= f.label :scanDate %><br />
    <%= f.text_field :scanDate %>
  </div>
  <div class="field">
    <%= f.label :scanTitle %><br />
    <%= f.text_field :scanTitle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/f1/f1Server/app/views/scannings/edit.html.erb
<h1>Editing scanning</h1>

<%= render 'form' %>

<%= link_to 'Show', @scanning %> |
<%= link_to 'Back', scannings_path %>

demo/f1/f1Server/app/views/scannings/index.html.erb
<h1>Listing scannings</h1>

<table>
  <tr>
    <th>Scanurl</th>
    <th>Scandate</th>
    <th>Scantitle</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scannings.each do |scanning| %>
  <tr>
    <td><%= scanning.scanUrl %></td>
    <td><%= scanning.scanDate %></td>
    <td><%= scanning.scanTitle %></td>
    <td><%= link_to 'Show', scanning %></td>
    <td><%= link_to 'Edit', edit_scanning_path(scanning) %></td>
    <td><%= link_to 'Destroy', scanning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scanning', new_scanning_path %>

demo/f1/f1Server/app/views/scannings/index1.html.erb
<!-- <h1>Listing scannings</h1>

<table>
  <tr>
    <th>Scanurl</th>
    <th>Scandate</th>
    <th>Scantitle</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scannings.each do |scanning| %>
  <tr>
    <td><%= scanning.scanUrl %></td>
    <td><%= scanning.scanDate %></td>
    <td><%= scanning.scanTitle %></td>
    <td><%= link_to 'Show', scanning %></td>
    <td><%= link_to 'Edit', edit_scanning_path(scanning) %></td>
    <td><%= link_to 'Destroy', scanning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scanning', new_scanning_path %> -->

demo/f1/f1Server/app/views/scannings/new.html.erb
<h1>New scanning</h1>

<%= render 'form' %>

<%= link_to 'Back', scannings_path %>

demo/f1/f1Server/app/views/scannings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Scanurl:</b>
  <%= @scanning.scanUrl %>
</p>

<p>
  <b>Scandate:</b>
  <%= @scanning.scanDate %>
</p>

<p>
  <b>Scantitle:</b>
  <%= @scanning.scanTitle %>
</p>


<%= link_to 'Edit', edit_scanning_path(@scanning) %> |
<%= link_to 'Back', scannings_path %>